platform :ios, "9.0"
target 'TestFeel'  do
  # pod 'Kiwi'
pod 'SGPagingView', '~> 1.7.2'
pod 'Masonry'
pod 'MJRefresh'
pod 'BRPickerView'
pod 'PNChart'
pod 'MBProgressHUD'
pod 'AFNetworking', '~> 4.0'
pod 'IQKeyboardManager'
pod 'TZImagePickerController/Basic'
pod 'SDWebImage'
end
